GET /rest/api/3/issue/KAN-3 HTTP/1.1
Host: click-app.atlassian.net
Authorization: Basic dmluY2UucGljdG9uQGdtYWlsLmNvbTpBVEFUVDN4RmZHRjB5NHZXYndUb0NTQU9na1dyRmwyTzI4UHdVd1pNRjRsYXVBOUdUT0xmbkxMd1hHZWtVLXBIWTZ3VmVmMHgzQzU4bEI3enZsTnBxTEdmTm8wQkFvdXJzZElWT1dmLS1tNlhOYWVER0pRN0VlTG1ZLTVRRWE0TWJOalVGVGhHcnpOLUFxbWd0NWZJXzVIVjJxYkJCNFpzTGxDalFMa0d0bm9wc3pubk1iR3g3X3M9RTgzMzYyQzQ=
Cookie: atlassian.xsrf.token=6922bf87d1659fced55d7062b5955b446e3af062_lin